# Streamlit in Snowflake apps run with a pre-installed version of the Streamlit library.
# For Streamlit Community Cloud, this pyproject.toml is also used to install dependencies.

[project]
name = "streamlit-app"
version = "0.0.1"
description = ""
requires-python = ">=3.11"

dependencies = [
    "streamlit>=1.54.0",
    "pandas",
    "snowflake-connector-python",
    "cryptography"
]

[tool.uv]
# earlier versions of numba require a python version < 3.11
constraint-dependencies = ["numba>=0.56.0"]