-- ============================================================
-- Care360 Copilot MVP — DDL
-- ============================================================

-- 1. Database
CREATE DATABASE IF NOT EXISTS CARE360_DB;

-- 2. Schemas
CREATE SCHEMA IF NOT EXISTS CARE360_DB.RAW;
CREATE SCHEMA IF NOT EXISTS CARE360_DB.CURATED;
CREATE SCHEMA IF NOT EXISTS CARE360_DB.DOCUMENTS;
CREATE SCHEMA IF NOT EXISTS CARE360_DB.APP;

-- 3. Structured tables in RAW
CREATE OR REPLACE TABLE CARE360_DB.RAW.PATIENTS (
    PATIENT_ID        VARCHAR(10)   NOT NULL,
    FIRST_NAME        VARCHAR(50)   NOT NULL,
    LAST_NAME         VARCHAR(50)   NOT NULL,
    DATE_OF_BIRTH     DATE          NOT NULL,
    GENDER            VARCHAR(10)   NOT NULL,
    RACE              VARCHAR(30),
    ETHNICITY         VARCHAR(30),
    ZIP_CODE          VARCHAR(10),
    STATE             VARCHAR(2),
    INSURANCE_TYPE    VARCHAR(20)   NOT NULL,   -- Medicare, Medicaid, Commercial, Uninsured
    PRIMARY_LANGUAGE  VARCHAR(30)   DEFAULT 'English',
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PATIENTS PRIMARY KEY (PATIENT_ID)
);

CREATE OR REPLACE TABLE CARE360_DB.RAW.ENCOUNTERS (
    ENCOUNTER_ID      VARCHAR(12)   NOT NULL,
    PATIENT_ID        VARCHAR(10)   NOT NULL,
    ENCOUNTER_DATE    DATE          NOT NULL,
    ENCOUNTER_TYPE    VARCHAR(20)   NOT NULL,   -- Inpatient, Outpatient, ER, Telehealth
    PROVIDER_NAME     VARCHAR(80),
    FACILITY_NAME     VARCHAR(100),
    DISCHARGE_DATE    DATE,
    CHIEF_COMPLAINT   VARCHAR(200),
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ENCOUNTERS PRIMARY KEY (ENCOUNTER_ID)
);

CREATE OR REPLACE TABLE CARE360_DB.RAW.DIAGNOSES (
    DIAGNOSIS_ID      VARCHAR(12)   NOT NULL,
    ENCOUNTER_ID      VARCHAR(12)   NOT NULL,
    PATIENT_ID        VARCHAR(10)   NOT NULL,
    ICD10_CODE        VARCHAR(10)   NOT NULL,
    DESCRIPTION       VARCHAR(200)  NOT NULL,
    IS_PRIMARY        BOOLEAN       DEFAULT FALSE,
    DIAGNOSED_DATE    DATE          NOT NULL,
    STATUS            VARCHAR(20)   DEFAULT 'Active',  -- Active, Resolved, Chronic
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIAGNOSES PRIMARY KEY (DIAGNOSIS_ID)
);

CREATE OR REPLACE TABLE CARE360_DB.RAW.MEDICATIONS (
    MEDICATION_ID     VARCHAR(12)   NOT NULL,
    PATIENT_ID        VARCHAR(10)   NOT NULL,
    DRUG_NAME         VARCHAR(100)  NOT NULL,
    NDC_CODE          VARCHAR(15),
    DOSAGE            VARCHAR(50),
    FREQUENCY         VARCHAR(50),
    ROUTE             VARCHAR(20)   DEFAULT 'Oral',
    PRESCRIBER        VARCHAR(80),
    START_DATE        DATE          NOT NULL,
    END_DATE          DATE,
    IS_ACTIVE         BOOLEAN       DEFAULT TRUE,
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_MEDICATIONS PRIMARY KEY (MEDICATION_ID)
);

CREATE OR REPLACE TABLE CARE360_DB.RAW.LAB_RESULTS (
    LAB_ID            VARCHAR(12)   NOT NULL,
    PATIENT_ID        VARCHAR(10)   NOT NULL,
    ENCOUNTER_ID      VARCHAR(12),
    TEST_NAME         VARCHAR(100)  NOT NULL,
    LOINC_CODE        VARCHAR(15),
    RESULT_VALUE      FLOAT,
    RESULT_UNIT       VARCHAR(20),
    REFERENCE_LOW     FLOAT,
    REFERENCE_HIGH    FLOAT,
    ABNORMAL_FLAG     VARCHAR(5),   -- H, L, HH, LL, NULL=normal
    COLLECTED_DATE    DATE          NOT NULL,
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LAB_RESULTS PRIMARY KEY (LAB_ID)
);

CREATE OR REPLACE TABLE CARE360_DB.RAW.CLAIMS (
    CLAIM_ID          VARCHAR(12)   NOT NULL,
    PATIENT_ID        VARCHAR(10)   NOT NULL,
    ENCOUNTER_ID      VARCHAR(12),
    SERVICE_DATE      DATE          NOT NULL,
    PROCEDURE_CODE    VARCHAR(10)   NOT NULL,
    PROCEDURE_DESC    VARCHAR(200),
    BILLED_AMOUNT     NUMBER(10,2)  NOT NULL,
    ALLOWED_AMOUNT    NUMBER(10,2),
    PAID_AMOUNT       NUMBER(10,2),
    PAYER             VARCHAR(50),
    CLAIM_STATUS      VARCHAR(20)   DEFAULT 'Paid',  -- Paid, Denied, Pending
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CLAIMS PRIMARY KEY (CLAIM_ID)
);

-- 4. Document tables in DOCUMENTS
CREATE OR REPLACE TABLE CARE360_DB.DOCUMENTS.RAW_DOCUMENTS (
    DOC_ID            VARCHAR(12)   NOT NULL,
    PATIENT_ID        VARCHAR(10),              -- NULL for regulatory docs
    DOC_TYPE          VARCHAR(30)   NOT NULL,   -- discharge_summary, progress_note, fda_alert, cms_policy
    FILENAME          VARCHAR(200)  NOT NULL,
    STAGE_PATH        VARCHAR(500),
    DOC_TEXT          TEXT,
    UPLOAD_DATE       DATE          DEFAULT CURRENT_DATE(),
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_RAW_DOCUMENTS PRIMARY KEY (DOC_ID)
);

CREATE OR REPLACE TABLE CARE360_DB.DOCUMENTS.DOCUMENT_CHUNKS (
    CHUNK_ID          VARCHAR(16)   NOT NULL,
    DOC_ID            VARCHAR(12)   NOT NULL,
    PATIENT_ID        VARCHAR(10),
    DOC_TYPE          VARCHAR(30)   NOT NULL,
    CHUNK_TEXT        TEXT           NOT NULL,
    CHUNK_INDEX       INT           NOT NULL,
    SOURCE_PAGE       INT,
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOCUMENT_CHUNKS PRIMARY KEY (CHUNK_ID)
);

-- 5. Internal stage for document files
CREATE STAGE IF NOT EXISTS CARE360_DB.DOCUMENTS.DOC_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- 6. File format for CSV loading
CREATE FILE FORMAT IF NOT EXISTS CARE360_DB.RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE;
